# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
# Properties
minecraft_version=1.21.1
loader_version_range=[1,)
neo_version=21.1.209
neo_version_range=[21,)
minecraft_version_range=[1.21.1]
maven_group=me.alexdevs
archives_base_name=classicperipherals
# Dependencies
parchment_version=2024.11.17

cctVersion=1.116.1

## Mod Properties

mod_id=classicperipherals
mod_name=Classic Peripherals
mod_license=MIT
mod_version=0.2.0
mod_group_id=me.alexdevs.classicperipherals
mod_authors=AlexDevs
mod_description=Classic Peripherals is a mod that adds a bunch of peripherals to CC: Tweaked.