name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Setup executable permissions
      run: chmod +x ./gradlew

    - name: Run Fabric datagen
      run: ./gradlew :fabric:runDatagen

    - name: Run NeoForge datagen
      run: ./gradlew :neoforge:runData

    - name: Build Fabric and NeoForge jars
      run: ./gradlew :fabric:build :neoforge:build

    - name: Upload Fabric jar
      uses: actions/upload-artifact@v4
      with:
        name: fabric-jar
        path: fabric/build/libs/*.jar

    - name: Upload NeoForge jar
      uses: actions/upload-artifact@v4
      with:
        name: neoforge-jar
        path: neoforge/build/libs/*.jar

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
